# == Schema Information
#
# Table name: dw_stock_out_at_dimensions # 出库时间纬度
#
#  id                 :integer          not null, primary key # 出库时间纬度
#  stock_out_at       :date                                   # 收购时间
#  stock_out_at_year  :integer                                # 收购日期(年)
#  stock_out_at_month :integer                                # 收购日期(月)
#

class Dw::StockOutAtDimension < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  validates :stock_out_at, presence: true, uniqueness: true
  validates :stock_out_at_year, presence: true
  validates :stock_out_at_month, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
