require "capistrano/setup"
require "capistrano/deploy"

require "capistrano/rvm"
require "capistrano/bundler"

require "capistrano/puma"
require "capistrano/puma/nginx"

Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
