# == Schema Information
#
# Table name: easy_loan_authority_roles # 车融易角色权限
#
#  id                      :integer          not null, primary key    # 车融易角色权限
#  name                    :string                                    # 权限名称
#  note                    :text                                      # 权限说明
#  authorities             :text             default([]), is an Array # 权限清单
#  easy_loan_sp_company_id :integer                                   # 和sp公司关联
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class EasyLoan::AuthorityRole < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :easy_loan_sp_company
  # validations ...............................................................
  validates :name, presence: true, uniqueness: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
