# == Schema Information
#
# Table name: easy_loan_cities # 车融易地区
#
#  id         :integer          not null, primary key # 车融易地区
#  name       :string                                 # 地区中文名称
#  pinyin     :string                                 # 地区拼音
#  zip_code   :string                                 # 地区邮编
#  score      :json             default({})           # 城市综合指数最小／最大／最可能分
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EasyLoan::City < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
