# == Schema Information
#
# Table name: easy_loan_rating_statements # 车融易评级说明
#
#  id         :integer          not null, primary key # 车融易评级说明
#  score      :integer                                # 分数
#  rate_type  :string                                 # 评级类型
#  content    :text                                   # 评级说明内容
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EasyLoan::RatingStatement < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  extend Enumerize
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  enumerize :rate_type,
            in: %i(
              comprehensive_rating operating_health industry_rating
            )
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
