在库车辆:
  在库车辆查询: 查询车来客中库存车辆信息
  车辆信息编辑: 收购车辆录入信息完善
  出库车辆编辑: 对已出库车辆进行编辑
  车辆新增入库: 新收购车辆入库录入
  在库车辆预定: 当客户定车后发起销售预定
  车辆销售定价: 为在库车辆制定标牌价、网络价、销售底价及经理底价
  车辆状态修改: 跟踪车辆状态并在车来客中记录（如整备中、在途、外借等）
  在库车辆出库: 当客户全款提车后操作车来客上的车辆出库
  销售底价查看: 可查看公司授权销售员可销售最低价格
  经理底价查看: 可查看公司确定销售组长可授权销售的最低价格
  车主寄卖信息查看: 查看非本人寄卖车辆的客户实收价格
  收购信息查看: "可查看非本人收购车辆的收购类型, 收购日期, 收购人"
  收购价格查看: 可查看非本人收购的车辆收购价
  合作信息查看: 查看车辆合作商家和合作价格
  库存转帮售: 库存车辆转为特卖车辆并在所有车来客商户中发布
  车辆操作历史查看: 查看车辆操作历史
  车辆库龄查看: 可查看车辆库龄
  网站车辆导入: 控制从网站导入公司车辆
  库存明细导出: 库存明细数据导出excel表格，方便统计查找
  在库车辆删除: 客户退车重新入库操作
  车辆图片上传: 可上传车辆图片
  维保详情查看: 是否可查看维保详情
出库车辆:
  已出库车辆查询: 查询车来客中出库车辆信息
  出库车辆回库:  对已出库车辆进行回库操作
  按揭信息查看:  查看车辆详情中按揭信息
  保险信息查看: 查看车辆保险信息
  销售成交信息查看: 可查看非本人销售历史成交价、成交日期、成交客户信息
  销售明细导出:  销售明细数据导出excel表格，方便统计查找
联盟管理:
  联盟车辆查询: 查询联盟中的车辆信息
  联盟底价查看: 查看公司车辆联盟底价
  联盟管理: 管理公司联盟
整备管理:
  整备信息录入: 可查看车辆的整备项目和描述
  整备信息查看: 查看车辆详情中整备信息
  整备费用查看: 可查看车辆的整备成本
牌证管理:
  牌证信息查看: 查看牌证信息
  牌证图片查看: 查看牌证图片
  牌证信息录入: 录入车辆的收购、销售过户资料查收和手续状态
  证件资料导出: 导出牌证中证件资料
客户管理:
  删除客户: 删除归属当前员工的某个客户
  代办客户预定/出库: "代办客户预定/出库权限"
  全部客户管理: 管理全部客户操作
  求购客户跟进: "控制能否查看 日常管理 -> 销售员"
  求购客户管理: "控制能否查看 日常管理 -> 销售经理"
  全部求购客户管理: "控制能否查看全部员工 日常管理 -> 销售经理"
  出售客户管理: "控制能否查看 日常管理 -> 收购经理"
  出售客户跟进: "控制能否查看 日常管理 -> 收购员"
  全部出售客户管理: "控制能否查看全部员工 日常管理 -> 收购经理"
  坐席录入: PC后台录入意向
  售后管理: 管理意向售后归属
车币管理:
  车币充值: 车币充值
  维保报告查询: 维保报告查询
系统设置:
  打印回单: 目前只有市场在用
  公司信息设置: 设置车来客内的公司信息：名称、电话、logo等
  员工管理: 为员工建立、删除帐号并分配权限
  角色管理: 公司角色管理
  业务设置: 设置客户渠道、库存预警天数、保险按揭公司、客户等级等
  库存统计查看: 查询统计信息
  微店管理权限: 管理查看微店的功能
  维保统计查看: 查询维保统计信息
财务管理:
  财务管理: 管理公司财务
  融资管理: 管理公司库存融资
