老板:
  note:
    老板
  authorities:
    在库车辆查询
    车辆信息编辑
    出库车辆编辑
    车辆新增入库
    在库车辆预定
    车辆销售定价
    车辆状态修改
    在库车辆出库
    销售底价查看
    经理底价查看
    车主寄卖信息查看
    收购信息查看
    收购价格查看
    合作信息查看
    库存转帮售
    车辆操作历史查看
    车辆库龄查看
    网站车辆导入
    库存明细导出
    在库车辆删除
    车辆图片上传
    已出库车辆查询
    出库车辆回库
    按揭信息查看
    保险信息查看
    销售成交信息查看
    销售明细导出
    联盟车辆查询
    联盟底价查看
    联盟管理
    整备信息录入
    整备信息查看
    整备费用查看
    牌证信息查看
    牌证信息录入
    证件资料导出
    删除客户
    代办客户预定/出库
    全部客户管理
    求购客户跟进
    求购客户管理
    全部求购客户管理
    出售客户管理
    出售客户跟进
    全部出售客户管理
    坐席录入
    打印回单
    公司信息设置
    员工管理
    角色管理
    业务设置
    库存统计查看
    微店管理权限
    车币充值
    维保报告查询
    维保详情查看
    维保统计查看
    牌证图片查看
    财务管理
    售后管理
    融资管理
管理员:
  note:
    管理员
  authorities:
    在库车辆查询
    车辆信息编辑
    车辆新增入库
    在库车辆预定
    车辆销售定价
    车辆状态修改
    在库车辆出库
    销售底价查看
    经理底价查看
    车主寄卖信息查看
    收购信息查看
    收购价格查看
    库存转帮售
    车辆操作历史查看
    库存明细导出
    在库车辆删除
    已出库车辆查询
    出库车辆回库
    按揭信息查看
    保险信息查看
    销售成交信息查看
    销售明细导出
    整备信息录入
    整备信息查看
    整备费用查看
    牌证信息查看
    牌证信息录入
    证件资料导出
    打印回单
    公司信息设置
    员工管理
    角色管理
    业务设置
    坐席录入
    求购客户跟进
    求购客户管理
    微店管理权限
    车币充值
    维保报告查询
收购师:
  note:
    车辆收购人员
  authorities:
    在库车辆查询
    车辆信息编辑
    车辆新增入库
    在库车辆预定
    车辆状态修改
    在库车辆出库
    库存明细导出
    在库车辆删除
    销售底价查看
    车辆操作历史查看
    已出库车辆查询
    出库车辆回库
    销售明细导出
    出售客户跟进
    车币充值
    维保报告查询
销售员:
  note:
    车辆销售人员
  authorities:
    在库车辆查询
    车辆信息编辑
    车辆新增入库
    在库车辆预定
    车辆状态修改
    在库车辆出库
    库存明细导出
    销售底价查看
    车辆操作历史查看
    已出库车辆查询
    出库车辆回库
    销售明细导出
    求购客户跟进
    车币充值
    维保报告查询
整备员:
  note:
    车辆维修整备人员
  authorities:
    在库车辆查询
    已出库车辆查询
    整备信息查看
    整备费用查看
    整备信息录入
牌证员:
  note:
    牌证员
  authorities:
    在库车辆查询
    已出库车辆查询
    牌证信息查看
    牌证信息录入
    证件资料导出
VIP客户:
  note:
    公司VIP客户福利，客户可随时在APP查看公司库存，提升客户荣誉感
  authorities:
    在库车辆查询
