default:
  基本参数:
    厂商:
      text
    级别:
      text
    发动机:
      text
    变速箱:
      text
    车身结构:
      text
  车身:
    长度(mm):
      text
    宽度(mm):
      text
    高度(mm):
      text
    轴距(mm):
      text
  发动机:
    发动机型号:
      text
    排量(mL):
      text
    进气形式:
      text
    气缸排列形式:
      text
    气缸数(个):
      text
    燃料形式:
      text
    环保标准:
      text
  变速箱:
    简称:
      text
    挡位个数:
      text
    变速箱类型:
      text
  安全装备 :
    主/副驾驶座安全气囊:
      select
    胎压监测装置:
      text
    零胎压继续行驶:
      text
    安全带未系提示:
      text
    ISOFIX儿童座椅接口:
      text
    发动机电子防盗:
      select
    车内中控锁:
      select
    遥控钥匙:
      select
    无钥匙启动系统:
      text
    无钥匙进入系统:
      text
  操控配置:
    ABS防抱死:
      select
    制动力分配(EBD/CBC等):
      select
    车身稳定控制(ESC/ESP/DSC等):
      text
  外部配置:
    电动天窗:
      select
    全景天窗:
      text
    运动外观套件:
      text
    电动吸合门:
      text
    电动后备厢:
      text
  内部配置:
    真皮方向盘:
      text
    方向盘换挡:
      text
    定速巡航:
      text
    前/后驻车雷达:
      select
    倒车视频影像:
      text
    行车电脑显示屏:
      select
  座椅配置:
    电动座椅记忆:
      text
    前/后排座椅加热:
      select
    前/后排座椅通风:
      select
    前/后排座椅按摩:
      select
  多媒体配置:
    GPS导航系统:
      text
    中控台彩色大屏:
      text
    蓝牙/车载电话:
      text
    车载电视:
      text
    CD支持MP3/WMA:
      select
    多媒体系统:
      text
  灯光配置:
    日间行车灯:
      text
    自动头灯:
      text
    转向辅助灯:
      text
    转向头灯:
      text
    前雾灯:
      select
    大灯清洗装置:
      text
    车内氛围灯:
      text
  玻璃/后视镜:
    前/后电动车窗:
      select
    车窗防夹手功能:
      select
    防紫外线/隔热玻璃:
      text
    后视镜电动调节:
      select
  空调/冰箱:
    空调控制方式:
      select
    后排独立空调:
      text
    后座出风口:
      text
    车载冰箱:
      text
  高科技配置:
    自动泊车入位:
      text
    发动机启停技术:
      text
    并线辅助:
      text
    车道偏离预警系统:
      text
    主动刹车/主动安全系统:
      text
    整体主动转向系统:
      text
    夜视系统:
      text
    自适应巡航:
      text
    全景摄像头:
      text
