first_letter:
  A:
    - 艾
    - 安
    - 敖
  B:
    - 巴
    - 白
    - 百
    - 柏
    - 班
    - 包
    - 鲍
    - 暴
    - 贝
    - 贲
    - 毕
    - 边
    - 卞
    - 别
    - 邴
    - 伯
    - 薄
    - 卜
    - 步
  C:
    - 蔡
    - 苍
    - 曹
    - 岑
    - 柴
    - 昌
    - 常
    - 晁
    - 巢
    - 车
    - 陈
    - 成
    - 程
    - 池
    - 充
    - 储
    - 褚
    - 淳
    - 从
    - 单
  D:
    - 戴
    - 党
    - 邓
    - 狄
    - 刁
    - 丁
    - 东
    - 董
    - 都
    - 窦
    - 堵
    - 杜
    - 端
    - 段
  E:
    - 鄂
  F:
    - 封
    - 符
    - 富
    - 傅
    - 丰
    - 房
    - 扶
    - 酆
    - 范
    - 贲
    - 方
    - 凤
    - 冯
    - 费
    - 伏
    - 樊
  G:
    - 盖
    - 干
    - 甘
    - 高
    - 郜
    - 戈
    - 葛
    - 耿
    - 弓
    - 公
    - 宫
    - 龚
    - 巩
    - 贡
    - 勾
    - 缑
    - 古
    - 谷
    - 顾
    - 关
    - 管
    - 广
    - 归
    - 桂
    - 郭
    - 国
  H:
    - 黄
    - 胡
    - 洪
    - 怀
    - 滑
    - 弘
    - 后
    - 宦
    - 侯
    - 惠
    - 红
    - 花
    - 杭
    - 郝
    - 和
    - 贺
    - 霍
    - 华
    - 何
    - 衡
    - 韩
    - 桓
    - 赫
    - 呼
    - 皇
  J:
    - 吉
    - 景
    - 季
    - 暨
    - 嵇
    - 居
    - 焦
    - 姬
    - 家
    - 计
    - 夹
    - 蒋
    - 贾
    - 纪
    - 经
    - 江
    - 姜
    - 靳
    - 井
    - 简
    - 鞠
    - 蓟
    - 郏
    - 荆
    - 冀
    - 金
  K:
    - 康
    - 匡
    - 况
    - 柯
    - 空
    - 寇
    - 隗
    - 夔
    - 阚
    - 孔
  L:
    - 赖
    - 蓝
    - 郎
    - 劳
    - 雷
    - 冷
    - 黎
    - 李
    - 厉
    - 利
    - 郦
    - 连
    - 廉
    - 梁
    - 廖
    - 蔺
    - 凌
    - 令
    - 刘
    - 柳
    - 龙
    - 隆
    - 娄
    - 卢
    - 鲁
    - 陆
    - 逯
    - 禄
    - 路
    - 闾
    - 吕
    - 栾
    - 罗
    - 骆
  M:
    - 麻
    - 马
    - 满
    - 茅
    - 梅
    - 蒙
    - 糜
    - 米
    - 宓
    - 苗
    - 闵
    - 明
    - 缪
    - 莫
    - 墨
    - 万
    - 牧
    - 慕
    - 穆
  N:
    - 那
    - 南
    - 能
    - 倪
    - 年
    - 聂
    - 乜
    - 宁
    - 牛
    - 农
  O:
    - 欧
  P:
    - 潘
    - 庞
    - 逄
    - 彭
    - 蓬
    - 皮
    - 平
    - 蒲
    - 濮
    - 濮
    - 浦
  Q:
    - 戚
    - 漆
    - 亓
    - 祁
    - 齐
    - 钱
    - 强
    - 乔
    - 谯
    - 秦
    - 邱
    - 秋
    - 仇
    - 裘
    - 曲
    - 屈
    - 璩
    - 全
    - 权
    - 阙
  R:
    - 冉
    - 壤
    - 饶
    - 任
    - 戎
    - 荣
    - 容
    - 融
    - 茹
    - 汝
    - 阮
    - 芮
  S:
    - 桑
    - 沙
    - 山
    - 单
    - 商
    - 上
    - 尚
    - 韶
    - 邵
    - 佘
    - 厍
    - 申
    - 莘
    - 沈
    - 慎
    - 盛
    - 师
    - 施
    - 石
    - 时
    - 史
    - 寿
    - 殳
    - 舒
    - 束
    - 双
    - 水
    - 司
    - 松
    - 宋
    - 苏
    - 宿
    - 孙
    - 索
  T:
    - 台
    - 太
    - 谈
    - 谭
    - 澹
    - 汤
    - 唐
    - 陶
    - 滕
    - 田
    - 通
    - 钭
    - 涂
    - 屠
    - 拓
  W:
    - 万
    - 汪
    - 王
    - 危
    - 微
    - 韦
    - 卫
    - 蔚
    - 魏
    - 温
    - 文
    - 闻
    - 闻
    - 翁
    - 沃
    - 乌
    - 邬
    - 巫
    - 吴
    - 伍
    - 武
  X:
    - 郗
    - 奚
    - 西
    - 习
    - 席
    - 夏
    - 夏
    - 鲜
    - 咸
    - 相
    - 向
    - 项
    - 萧
    - 谢
    - 解
    - 幸
    - 邢
    - 熊
    - 胥
    - 须
    - 徐
    - 许
    - 轩
    - 宣
    - 薛
    - 荀
  Y:
    - 闫
    - 严
    - 阎
    - 颜
    - 晏
    - 燕
    - 羊
    - 阳
    - 杨
    - 仰
    - 养
    - 姚
    - 叶
    - 伊
    - 易
    - 益
    - 羿
    - 阴
    - 殷
    - 尹
    - 印
    - 应
    - 雍
    - 尤
    - 游
    - 有
    - 于
    - 余
    - 於
    - 鱼
    - 俞
    - 喻
    - 虞
    - 宇
    - 禹
    - 郁
    - 尉
    - 元
    - 袁
    - 岳
    - 越
    - 乐
    - 云
  Z:
    - 赵
    - 宰
    - 宰
    - 昝
    - 臧
    - 曾
    - 翟
    - 詹
    - 湛
    - 张
    - 章
    - 仉
    - 查
    - 长
    - 甄
    - 郑
    - 支
    - 终
    - 钟
    - 钟
    - 仲
    - 周
    - 朱
    - 诸
    - 竺
    - 祝
    - 颛
    - 庄
    - 卓
    - 子
    - 訾
    - 宗
    - 邹
    - 祖
    - 左
