export Acquisition from './Acquisition'
export Basic from './Basic'
export Price from './Price'
export Description from './Description'
export Sales from './Sales'
export Images from './Images'
export Maintaining from './Maintaining'
export Features from './Features'
