# == Schema Information
#
# Table name: dw_acquisition_facts # 入库事实
#
#  id                       :integer          not null, primary key # 入库事实
#  car_id                   :integer                                # 车辆ID
#  car_dimension_id         :integer                                # 车辆维度ID
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  acquisition_price_cents  :integer          default(0)            # 收购价格
#  acquirer_id              :integer                                # 收购员
#  acquisition_type         :string                                 # 收购类型
#  acquired_at_dimension_id :integer                                # 收购日期纬度
#

class Dw::AcquisitionFact < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :car, -> { with_deleted }
  belongs_to :acquired_at_dimension, class_name: "Dw::AcquiredAtDimension"
  belongs_to :car_dimension, class_name: "Dw::CarDimension"
  belongs_to :acquirer, -> { with_deleted }, class_name: "User"

  # validations ...............................................................
  validates :car_id, presence: true, uniqueness: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
