# == Schema Information
#
# Table name: car_appointments # 预约看车
#
#  id         :integer          not null, primary key # 预约看车
#  car_id     :integer                                # 车辆ID
#  phone      :string                                 # 手机
#  name       :string                                 # 姓名
#  seller_id  :integer                                # 销售员ID
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  company_id :integer                                # 公司ID
#

class CarAppointment < ActiveRecord::Base
  # 不再维护的表

  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :company
  belongs_to :seller, class_name: "User", foreign_key: :seller_id
  belongs_to :car
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
