# == Schema Information
#
# Table name: chat_sessions
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  nick_name   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  target_id   :integer
#  target_type :string
#

class ChatSession < ActiveRecord::Base
  # accessors .................................................................
  delegate :avatar,
           to: :user,
           allow_nil: true
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :user
  belongs_to :target, polymorphic: true
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................

  def nickname
    nick_name || user.name
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
