# == Schema Information
#
# Table name: cooperation_companies # 合作商家
#
#  id         :integer          not null, primary key # 合作商家
#  company_id :integer                                # 公司ID
#  name       :string                                 # 名称
#  deleted_at :datetime                               # 删除时间
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CooperationCompany < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :company
  has_many :cooperation_company_relationships

  # validations ...............................................................
  validates :name, uniqueness_without_deleted: { scope: :company_id }, if: :name?
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  acts_as_paranoid
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
