# == Schema Information
#
# Table name: detection_reports # 检测报告
#
#  id            :integer          not null, primary key # 检测报告
#  report_type   :string                                 # 报告类型
#  car_id        :integer                                # 关联的车辆id
#  url           :string                                 # 生成报告的地址
#  platform_name :string                                 # 对应的检测平台名
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  images_count  :integer
#

class DetectionReport < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  extend Enumerize
  extend EnumerizeWithGroups
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :car
  has_many :images, as: :imageable, class_name: Image.name
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  enumerize :report_type, in: %i(report image pdf)
  accepts_nested_attributes_for :images, allow_destroy: true
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
