# == Schema Information
#
# Table name: owner_companies # 归属车商
#
#  id         :integer          not null, primary key # 归属车商
#  name       :string                                 # 车商名
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  shop_id    :integer                                # 车商所属的分店
#  company_id :integer                                # 所属车商
#

class OwnerCompany < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................

  has_many :cars, dependent: :nullify
  belongs_to :shop
  belongs_to :company

  delegate :name, to: :shop, prefix: true, allow_nil: true
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
