# == Schema Information
#
# Table name: token_packages # 车币套餐
#
#  id            :integer          not null, primary key # 车币套餐
#  name          :string                                 # 名称
#  title         :string                                 # 标题
#  description   :string                                 # 描述
#  price_cents   :integer                                # 价格
#  balance       :integer                                # 车币
#  extra_balance :integer                                # 赠送车币
#

class TokenPackage < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  include Priceable
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  price_yuan :price
  # class methods .............................................................
  # public instance methods ...................................................
  def total_balance
    balance + extra_balance
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
