# == Schema Information
#
# Table name: user_chat_groups
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  chat_group_id :integer
#  nick_name     :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class UserChatGroup < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :user
  belongs_to :chat_group
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
