# == Schema Information
#
# Table name: warranties # 质保等级
#
#  id         :integer          not null, primary key # 质保等级
#  company_id :integer                                # 公司ID
#  name       :string                                 # 名称
#  fee_cents  :integer                                # 费用
#  deleted_at :datetime                               # 删除时间
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  note       :text                                   # 说明
#

class Warranty < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  include Priceable
  # relationships .............................................................
  belongs_to :company
  has_many :cars
  # validations ...............................................................
  validates :name, presence: true, uniqueness_without_deleted: { scope: :company_id }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  acts_as_paranoid

  price_yuan :fee

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
