# == Schema Information
#
# Table name: alliance_channels # 联盟公司意向渠道
#
#  id         :integer          not null, primary key # 联盟公司意向渠道
#  company_id :integer                                # 公司ID
#  name       :string                                 # 名称
#  note       :text                                   # 备注
#  deleted_at :datetime                               # 删除时间
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class AllianceCompany::Channel < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :company, class_name: "AllianceCompany::Company"
  # validations ...............................................................
  validates :name, presence: true, uniqueness_without_deleted: { scope: :company_id }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  acts_as_paranoid
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
