# == Schema Information
#
# Table name: dashboard_operation_records
#
#  id             :integer          not null, primary key
#  staff_id       :integer                                # 操作员工ID
#  operation_type :string                                 # 操作类型
#  content        :jsonb                                  # 操作内容
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

module Dashboard
  class OperationRecord < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    # relationships .............................................................
    belongs_to :staff
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
