# == Schema Information
#
# Table name: tf_t_stock_cooper
#
#  stock_cooper_id :integer          not null, primary key
#  cooper_corp_id  :integer
#  stock_id        :integer
#  cooper_price    :integer
#  create_time     :datetime
#

module Che3bao
  class CooperationCompanyRelationship < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    include Appropriatable
    belongs_to :stock
    belongs_to :cooperation_company, foreign_key: :cooper_corp_id
    # relationships .............................................................
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "tf_t_stock_cooper"
    self.primary_key = "stock_cooper_id"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
