# == Schema Information
#
# Table name: td_b_cust_level
#
#  level_code    :integer          not null, primary key
#  corp_id       :integer
#  level_name    :string(30)
#  display_order :integer
#  valid_tag     :string(1)
#  create_time   :datetime
#  follow_days   :integer          default(-1)
#

module Che3bao
  class CustomerLevel < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    include Appropriatable
    # relationships .............................................................
    belongs_to :corp
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "td_b_cust_level"
    self.primary_key = "level_code"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
