# == Schema Information
#
# Table name: td_b_defeat_reason
#
#  defeat_reason_id :integer          not null
#  corp_id          :integer
#  reason_name      :string(40)
#  valid_tag        :string(1)
#  create_time      :datetime
#  update_time      :datetime
#

module Che3bao
  class DefeatReason < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    # relationships .............................................................
    belongs_to :corp
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "td_b_defeat_reason"
    self.primary_key = "fefeat_reason_id"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
