# == Schema Information
#
# Table name: td_b_region
#
#  id          :integer          not null, primary key
#  parent_id   :integer
#  region_name :string(40)
#  region_type :integer                                # 0-???;1-市;2-地级市;
#  region_desc :string(255)
#  status      :string(1)                              # 0：无效；1：有效：2：删除；
#

module Che3bao
  class Region < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    # relationships .............................................................
    belongs_to :parent, class_name: "Region", foreign_key: :parent_id
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "td_b_region"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
