# == Schema Information
#
# Table name: td_b_stock_locate
#
#  id          :integer          not null, primary key
#  corp_id     :integer
#  locate_name :string(30)
#  status      :string(1)                              # 0：无效；1：有效：2：删除；
#  remark      :string(500)
#  create_time :datetime
#  store_no    :string(64)
#

module Che3bao
  class Shop < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    include Appropriatable
    # relationships .............................................................
    belongs_to :corp
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "td_b_stock_locate"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
