# == Schema Information
#
# Table name: td_b_warranty_level
#
#  id           :integer          not null, primary key
#  corp_id      :integer
#  level_name   :string(100)      not null
#  level_desc   :string(255)                              # 0-网站;1-电??;2-哪有??;3-??他渠道
#  warranty_fee :integer
#  STATUS       :string(1)                                # 0-表示不启用;1-启用
#  create_time  :datetime         default(NULL), not null
#

module Che3bao
  class Warranty < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    include Appropriatable
    # relationships .............................................................
    belongs_to :corp

    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "td_b_warranty_level"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
