在库车辆:
  在库车辆查询: 查询车来客中库存车辆信息
  车辆信息编辑: 收购车辆录入信息完善
  车辆图片上传: 可上传车辆图片
  车辆状态修改: 跟踪车辆状态并在车来客中记录（如整备中、在途、外借等）
  库存明细导出: 库存明细数据导出excel表格，方便统计查找
  销售底价查看: 可查看公司授权销售员可销售最低价格
  经理底价查看: 可查看公司确定销售组长可授权销售的最低价格
  收购信息查看: "可查看非本人收购车辆的收购类型, 收购日期, 收购人"
  合作信息查看: 查看车辆合作商家和合作价格
  保险信息查看: 查看车辆的保险信息
  车辆库龄查看: 可查看车辆库龄
  车主寄卖信息查看: 查看非本人寄卖车辆的客户实收价格
  车辆操作历史查看: 查看车辆操作历史
出库车辆:
  已出库车辆查询: 查询车来客中出库车辆信息
  按揭信息查看:  查看车辆详情中按揭信息
  销售成交信息查看: 可查看非本人销售历史成交价、成交日期、成交客户信息
联盟管理:
  联盟车辆查询: 查询联盟中的车辆信息
  联盟底价查看: 查看公司车辆联盟底价
  联盟管理: 管理公司联盟
整备管理:
  整备信息查看: 查看车辆详情中整备信息
  整备费用查看: 可查看车辆的整备成本
牌证管理:
  牌证信息查看: 查看牌证信息
  证件资料导出: 导出牌证中证件资料
客户管理:
  全部客户管理: 管理全部客户操作
系统设置:
  员工管理: 为员工建立、删除帐号并分配权限
  角色管理: 公司角色管理
  业务设置: 设置客户渠道、库存预警天数、保险按揭公司、客户等级等
