车窗配置:
  手动车窗: 手动车窗
  电动车窗: 电动车窗
  普通车窗: 普通车窗
  全景车窗: 全景车窗
  玻璃顶: 玻璃顶

照明配置:
  疝气大灯: 疝气大灯
  随动大灯: 随动大灯
  大灯自动清洗: 大灯自动清洗

空调配置:
  手动空调: 手动空调
  自动空调: 自动空调
  分区恒温: 分区恒温

被动安全装置:
  驾驶座单气囊: 驾驶座单气囊
  双气囊: 双气囊
  膝部气囊: 膝部气囊
  ABS防抱死: ABS防抱死
  制动力分配: 制动力分配
  车身稳定控制: 车身稳定控制
  牵引力控制: 牵引力控制
  气帘: 气帘

主动安全装置:
  中控锁: 中控锁
  遥控启动: 遥控启动
  无钥启动: 无钥启动
  定速巡航: 定速巡航
  倒车影像: 倒车影像
  全景可视: 全景可视
  倒车雷达: 倒车雷达
  自动泊车: 自动泊车
  并线辅助: 并线辅助
  转向动力: 转向动力
  陡坡缓降: 陡坡缓降
  换档拨片: 换档拨片
  可变悬架: 可变悬架
  自动驻车/上坡辅助: 自动驻车/上坡辅助

座椅配置:
  真皮座椅: 真皮座椅
  电动座椅: 电动座椅
  座椅加热: 座椅加热
  座椅通风: 座椅通风
  按摩座椅: 按摩座椅
  电动记忆座椅: 电动记忆座椅

外观配置:
  电动反光镜: 电动反光镜
  感应雨刷: 感应雨刷
  电动后备箱: 电动后备箱

内饰配置:
  多功能方向盘: 多功能方向盘
  电动遮阳帘: 电动遮阳帘
  反光镜电动折叠: 反光镜电动折叠

通讯娱乐:
  GPS导航: GPS导航
  CD: CD
  DVD: DVD
  MP3接口: MP3接口

加装配置:
  防爆棍: 防爆棍
  后扰流板: 后扰流板
  延时熄火装置: 延时熄火装置
  日间行车灯: 日间行车灯
  轮眉: 轮眉
  迎宾踏板: 迎宾踏板
  车顶行李架: 车顶行李架
  电动后备箱: 电动后备箱
  大灯清洗: 大灯清洗
  无骨雨刷: 无骨雨刷
  遥控钥匙: 遥控钥匙
  触屏机头: 触屏机头
  转向助力: 转向助力

改装配置:
  轮毂: 轮毂
  前端中网风格栅: 前端中网风格栅
  太阳膜: 太阳膜
  车身彩条: 车身彩条
  真皮座椅: 真皮座椅
  全网隔音: 全网隔音
