AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/*"
    - "lib/templates/**/*"
    - "app/models/che3bao/**"
    - "tmp/**/*"
    - "lib/plugins/wechat/message/*"
    - "lib/engines/dashboard/**/*"
    - "db/seeds.rb"
    - "lib/tasks/platform_brand_initialize.rake"
Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FindBy:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 700

Metrics/ParameterLists:
  Max: 6

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/NumericLiterals:
  Description: >-
                 Add underscores to large numeric literals to improve their
                 readability.
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics'
  Enabled: false
