# frozen_string_literal: true

# rubocop:disable Bundler/OrderedGems
# source "https://rubygems.org"
source "https://gems.ruby-china.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby "~> 2.3.0"

gem "rails", "~> 5.0.1"
gem "pg", "~> 0.18"
gem "puma", "~> 3.0"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.2"

gem "figaro", "~> 1.1.1"

gem "jquery-rails", "~> 4.2.2"
gem "turbolinks", "~> 5"
gem "jbuilder", "~> 2.5"
gem "redis", "~> 3.0"
gem "bcrypt", "~> 3.1.7"
gem "thor", "0.19.1"
gem "device_detector"
gem "bootstrap-sass", "~> 3.3.7"
gem "font-awesome-sass", "~> 4.7.0"
gem "exception_notification", "~> 4.2.0"
gem "connection_pool", "~> 2.2.0"
gem "kgio", "~> 2.10.0"
gem "dalli", "~> 2.7.0"
gem "kaminari", "~> 1.0.1"

gem "enumerize", "~> 2.0.0"
gem "enumerize_with_groups", "~> 0.3.0"
gem "lodash-rails"
gem "pundit", "~> 1.1.0"
gem "draper", "~> 3.0.0" # view 层Decorator
gem "redis-rails" # redis缓存

source "https://rails-assets.org/" do
  gem "rails-assets-adminlte", "~> 2.3.11"
  gem "rails-assets-swiper", "~> 3.4.1"
end
# 日期选择组件
gem "momentjs-rails", ">= 2.9.0"
gem "bootstrap3-datetimepicker-rails", "~> 4.17.47"
# 云片
gem "yunpian"
# 微信
gem "roxml", "~> 3.3.0"
gem "upsert", "~> 2.1.0"
# API
gem "rest-client", "~> 2.0.0"
gem "jwt", "~> 1.5.0"
# for param!
gem "rails_param", github: "nicolasblanco/rails_param"
# for response_json
gem "multi_json", "~> 1.12.0"
# 时间差计算
gem "time_difference"
# 图片上传
gem "carrierwave-aliyun", "~> 0.8.0"

gem "chinese_pinyin"
# Ping++ 支付
gem "pingpp"
# 解决跨域 ajax 调用, 因为微信支付只能用固定的域名
gem "rack-cors", require: "rack/cors"

# Ping++ 支付
gem "pingpp"
# 解决跨域 ajax 调用, 因为微信支付只能用固定的域名
gem "rack-cors", require: "rack/cors"
gem "whenever", require: false

group :development, :test do
  gem "migration_comments"
  gem "rspec-rails", "~> 3.0"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem "web-console", ">= 3.3.0"
  gem "listen", "~> 3.0.5"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "annotate"

  # Deployment
  gem "capistrano"
  gem "capistrano-rails"
  gem "capistrano-rvm"
  gem "capistrano3-puma"
  gem "capistrano-slackify"
  gem "capistrano-sidekiq", github: "LcpMarvel/capistrano-sidekiq"
  gem "capistrano-db-tasks", require: false

  gem "rubocop", require: false
end

group :development, :staging, :test do
  gem "bullet", "~> 5.5.0"
  gem "act-fluent-logger-rails", "~> 0.3.0"
  gem "lograge", "~> 0.4.0"
  gem "byebug", platform: :mri
  gem "pry-byebug"
end

group :test do
  gem "database_cleaner"
  gem "vcr"
  gem "webmock"
  gem "rails-controller-testing"
  # gem "params_builder"
  # gem "test_after_commit"
end
