# == Schema Information
#
# Table name: easy_loan_sp_companies # 借款的sp公司
#
#  id         :integer          not null, primary key # 借款的sp公司
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EasyLoan::SpCompany < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  has_many :users, class_name: "EasyLoan::User"
  has_many :loan_bills, class_name: "EasyLoan::LoanBill"
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
