platform :ios, '9.0'

def shared_pods
  use_frameworks!
  pod 'RxAlamofire', '~> 4.2.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Kingfisher', '~> 4.7.0'
  pod 'ESPullToRefresh', '~> 2.7'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'RealmSwift', '~> 3.5.0'
  pod 'Pageboy', '~> 2.0'
  pod 'STRegex', '~> 1.1'
  pod 'SwiftIcons', '~> 2.0.1'
  pod 'ZMTimeLineView', '~> 0.5.0'
  pod 'ZMKnife', '~> 0.2.1'
  pod 'PGDatePicker', :git => 'https://github.com/superbug/PGDatePicker.git'
  pod 'JPush', '~> 3.0.7'
  pod 'PgyUpdate'
  pod 'SwiftDate', '~> 4.5.1'
  pod 'IQKeyboardManagerSwift', '~> 6.0.3'
  pod 'AMap2DMap'
  pod 'AMapLocation'
  pod 'AFNetworking', '~> 3.0'
end

target 'EasyLoan' do
  shared_pods
end

target 'EasyLoanTest' do
  shared_pods
end
