# == Schema Information
#
# Table name: tf_m_alliance_mem
#
#  alliance_mem_id :integer          not null, primary key
#  mem_corp        :integer
#  alliance_id     :integer
#  mem_status      :string(1)                              # 0：已加入联盟；1：已退出联盟
#  join_time       :datetime
#  exit_time       :datetime
#

module Che3bao
  class AllianceRelationship < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    include Appropriatable
    belongs_to :corp, foreign_key: :mem_corp, class_name: Corp.name
    belongs_to :alliance
    # relationships .............................................................
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "tf_m_alliance_mem"
    self.primary_key = "alliance_mem_id"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
