# == Schema Information
#
# Table name: tf_m_alliance_info
#
#  alliance_id       :integer          not null, primary key
#  alliance_name     :string(255)
#  alliance_desc     :string(500)
#  own_corp          :integer
#  create_staff      :integer
#  create_time       :datetime
#  valid_tag         :string(1)                              # 0：无效；1：有效
#  alliance_portrait :string(255)
#

module Che3bao
  class Alliance < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    include Appropriatable
    belongs_to :corp, foreign_key: :own_corp, class_name: Corp.name

    has_many :alliance_relationships
    has_many :corps, through: :alliance_relationships, source: :corp
    # relationships .............................................................
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "tf_m_alliance_info"
    self.primary_key = "alliance_id"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
