# == Schema Information
#
# Table name: td_b_infosource
#
#  id            :integer          not null, primary key
#  corp_id       :integer
#  source_name   :string(30)                             # 1-置换；2-400；3-拍卖；4-门店；5-??存车；...
#  group_code    :integer                                # -1：系统设定来源（不允许后台维???）；0-网站;1-???台;2-哪有车;3-其他渠道；4-门店；5??电话；
#  source_type   :integer                                # 0-车源；1-客源；2-库存；
#  display_order :integer
#  valid_tag     :string(1)                              # 0-不启用;1-启用
#  remark        :string(20)
#  create_time   :datetime
#  create_type   :string(1)
#

module Che3bao
  class Channel < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    include Appropriatable
    belongs_to :corp
    # relationships .............................................................
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "td_b_infosource"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
