# == Schema Information
#
# Table name: td_b_invalid_reason
#
#  invalid_reason_id :integer          not null, primary key
#  corp_id           :integer
#  reason_name       :string(255)
#  valid_tag         :string(1)
#  create_time       :datetime
#  update_time       :datetime
#

module Che3bao
  class InvalidReason < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    # relationships .............................................................
    belongs_to :corp
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "td_b_invalid_reason"
    self.primary_key = "invalid_reason_id"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
