# == Schema Information
#
# Table name: tf_t_vehicle_attach
#
#  id             :integer          not null, primary key
#  vehicle_id     :integer          not null
#  attach_id      :integer          not null
#  value          :string(5)
#  src_pic_addr   :string(2000)
#  small_pic_addr :string(2000)
#  pic_name       :string(255)
#  upload_staff   :integer
#  upload_time    :datetime
#

module Che3bao
  class VehicleAttachRelationship < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    # relationships .............................................................
    belongs_to :vehicle
    belongs_to :vehicle_attach, foreign_key: :attach_id, class_name: VehicleAttach.name
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "tf_t_vehicle_attach"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
