# == Schema Information
#
# Table name: td_b_attach_param
#
#  id          :integer          not null, primary key
#  code        :string(20)
#  name        :string(40)
#  attach_type :string(1)                              # 1：车辆附件;0:车辆资料
#  value_json  :string(100)
#  status      :string(1)                              # 0：无效；1：有效：2：删除；
#

module Che3bao
  class VehicleAttach < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    include Che3baoConnection
    # relationships .............................................................
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    self.table_name = "td_b_attach_param"
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
