# == Schema Information
#
# Table name: advertisements # 广告
#
#  id           :integer          not null, primary key # 广告
#  title        :string                                 # 标题
#  image_url    :string                                 # 图片地址
#  redirect_url :string                                 # 跳转链接
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  state        :string           default("enabled")    # 是否启用
#  show_seconds :integer                                # 广告展示时长
#

class Advertisement < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
