# == Schema Information
#
# Table name: authority_roles # 权限名称
#
#  id          :integer          not null, primary key    # 权限名称
#  company_id  :integer
#  name        :string                                    # 名称
#  authorities :text             default([]), is an Array # 权限
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  note        :text                                      # 备注
#

class AuthorityRole < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :company

  has_many :authority_role_relationships, dependent: :delete_all
  has_many :users,
           through: :authority_role_relationships,
           source: :user
  # validations ...............................................................

  validates :name, presence: true, uniqueness: { scope: :company_id }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
