# == Schema Information
#
# Table name: car_info_publish_records # 收车信息发送记录
#
#  id                      :integer          not null, primary key # 收车信息发送记录
#  acquisition_car_info_id :integer                                # 对应的收车信息
#  chatable_id             :integer                                # 发送到的群组或个人
#  chatable_type           :string                                 # 发送到的群组或个人
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class CarInfoPublishRecord < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :acquisition_car_info
  belongs_to :chatable, polymorphic: true
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
