# == Schema Information
#
# Table name: cooperation_company_relationships # 合作商家关联表
#
#  id                      :integer          not null, primary key # 合作商家关联表
#  car_id                  :integer                                # 车辆ID
#  cooperation_company_id  :integer                                # 合作商家ID
#  cooperation_price_cents :integer                                # 合作价格
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class CooperationCompanyRelationship < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  include Priceable
  # relationships .............................................................
  belongs_to :cooperation_company, -> { with_deleted }
  belongs_to :car, -> { with_deleted }
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  price_wan :cooperation_price
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
