# == Schema Information
#
# Table name: intention_expirations # 意向过期时间
#
#  id            :integer          not null, primary key # 意向过期时间
#  company_id    :integer                                # 公司ID
#  recovery_time :integer          not null              # 过期天数
#  note          :text                                   # 备注
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class IntentionExpiration < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :company
  # validations ...............................................................
  # 目前每个公司只有统一的意向过期时间设置, 以后可能根据客户等级细分
  validates :company_id, uniqueness: true
  validates :recovery_time, presence: true,
                            numericality: { only_integer: true,
                                            greater_than: 0 }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
