# == Schema Information
#
# Table name: intention_push_cars # 看过的车辆
#
#  id                        :integer          not null, primary key # 看过的车辆
#  intention_id              :integer                                # 意向ID
#  intention_push_history_id :integer                                # 意向跟进历史ID
#  car_id                    :integer                                # 车辆ID
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#

class IntentionPushCar < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :intention_push_history
  belongs_to :intention
  belongs_to :car
  # validations ...............................................................
  validates :intention_id, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
