# == Schema Information
#
# Table name: login_histories
#
#  id            :integer          not null, primary key
#  user_id       :integer                                # 用户ID
#  company_id    :integer                                # 公司ID
#  ip            :string                                 # IP地址
#  user_agent    :string                                 # UserAgent
#  mac_address   :string                                 # MAC地址
#  device_number :string                                 # APP设备号
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class LoginHistory < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :user
  belongs_to :company
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
