# == Schema Information
#
# Table name: maintenance_settings
#
#  id                      :integer          not null, primary key
#  chejianding_unit_price  :decimal(8, 2)    default(17.0)
#  ant_queen_unit_price    :decimal(8, 2)    default(29.0)
#  cha_doctor_unit_price   :decimal(8, 2)    default(12.0)
#  dashenglaile_unit_price :decimal(8, 2)    default(12.0)
#

class MaintenanceSetting < ActiveRecord::Base
  # accessors .................................................................
  # extends ...................................................................
  # includes ..................................................................
  include ActiveRecord::Singleton
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
