# == Schema Information
#
# Table name: dashboard_company_properties # 公司运营属性表
#
#  id         :integer          not null, primary key # 公司运营属性表
#  company_id :integer                                # 公司ID
#  staff_id   :integer                                # 服务顾问ID
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module Dashboard
  class CompanyProperty < ActiveRecord::Base
    # accessors .................................................................
    # extends ...................................................................
    # includes ..................................................................
    # relationships .............................................................
    belongs_to :company
    belongs_to :staff
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
  end
end
